$testobject {

	$testcase 1 {
		$name "Dummy"
		$uuid "b48ef5ff-4412-4ed3-a7f9-45ef7130f848"

		$teststep 1.1 {
			$name ""
			$uuid "d0d4ee77-3a47-4612-aa0c-3b8f28db28c2"
			$inputs {
				a = 2
				b = 3
				c = 5
			}
			$outputs {
				c = 5
				return 5
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}

		$teststep 1.2 {
			$name ""
			$uuid "c33564a8-40c6-434f-b03c-37db02b6f9a9"
			$inputs {
				a = 4
				b = 5
				c = 9
			}
			$outputs {
				c = 9
				return 9
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}

		$teststep 1.3 {
			$name ""
			$uuid "2feabb33-3faf-4800-9b84-83c248bef514"
			$inputs {
				a = 5
				b = 9
				c = 14
			}
			$outputs {
				c = 14
				return 14
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}
}