$testobject {

	$testcase 1 {
		$name "Dummy"
		$uuid "5a438e64-a485-4272-863e-4d0609b7348a"

		$teststep 1.1 {
			$name ""
			$uuid "de7d2905-d547-477e-9776-062f387a4613"
			$inputs {
				x = 4
				y = 2
				z = 2
			}
			$outputs {
				z = 2
				return 2
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}

		$teststep 1.2 {
			$name ""
			$uuid "0b11eee5-b674-467c-a879-acb0b654d2c9"
			$inputs {
				x = 9
				y = 6
				z = 3
			}
			$outputs {
				z = 3
				return 3
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}

		$teststep 1.3 {
			$name ""
			$uuid "6f11d79c-ec1b-402e-bf84-3519d7832ed6"
			$inputs {
				x = 8
				y = 3
				z = 5
			}
			$outputs {
				z = 5
				return 5
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}
}