#
# This file was generated by Tessy, do not edit!
#
./.idbbuild/add.c.i : C:/Users/Sowjanya/Desktop/JENKIN~4/tessy/add.c
./.idbbuild/mul.c.i : C:/Users/Sowjanya/Desktop/JENKIN~4/tessy/mul.c
./.idbbuild/sub.c.i : C:/Users/Sowjanya/Desktop/JENKIN~4/tessy/sub.c
