#
# This file was generated by Tessy, do not edit!
#
./.idbbuild/add.c.i : C:/Users/Sowjanya/Desktop/add.c
./.idbbuild/mul.c.i : C:/Users/Sowjanya/Desktop/mul.c
./.idbbuild/sub.c.i : C:/Users/Sowjanya/Desktop/sub.c
